In [12]:
import numpy as np;
A=np.array([[1,2],[3,4]])
B=np.array([[6,7],[8,9]])
print(f"Matrix A:\n{A}")
print(f"Matrix B:\n{B}")
print(f"Matrix Addition:\n{A+B}")
print(f"Matrix subtraction:\n{A-B}")
print(f"Matrix multiplication:\n{A*B}")
print(f"Transpose of matrix A:\n{A.T}")








Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[6 7]
 [8 9]]
Matrix Addition:
[[ 7  9]
 [11 13]]
Matrix subtraction:
[[-5 -5]
 [-5 -5]]
Matrix multiplication:
[[ 6 14]
 [24 36]]
Transpose of matrix A:
[[1 3]
 [2 4]]
